export const name = 'Techcrunch',
  sortParameters = ['top', 'latest'],
  id = 'techcrunch',
  sortBy = 'top',
  news = [{
    author: 'Reporter',
    title: 'Reasons to be cheerful',
    description: null,
    url: 'https://foo.hotnews.com',
    urlImage: 'https://bar.hotnews.com/image.png',
    date: '2017-05-21T14:40:57Z',
  },
  {
    author: 'Repo',
    title: 'Reasons to be cheerful2',
    description: 'There are many reasons to be cheerful. Number one...',
    url: 'https://foo.hotnews2.com',
    urlImage: 'https://bar.hotnews.com/image.png',
    date: '2017-05-21T14:40:57B',
  }],
  sortedNews = [{
    author: 'Repo',
    title: 'Reasons to be cheerful2',
    description: 'There are many reasons to be cheerful. Number one...',
    url: 'https://foo.hotnews2.com',
    urlImage: 'https://bar.hotnews2.com/image.png',
    date: '2017-05-21T14:40:57B',
  },
  {
    author: 'Reporter',
    title: 'Reasons to be cheerful',
    description: 'There are many reasons to be cheerful. Number one...',
    url: 'https://foo.hotnews.com',
    urlImage: 'https://bar.hotnews.com/image.png',
    date: '2017-05-21T14:40:57Z',
  }],
  sources = [{
    id: 'ars-technica',
    name: 'Ars Technica',
    description: 'The PC enthusiast\'s resource. Power users..',
    category: 'technology',
    sortBy: [
      'top',
      'latest',
    ],
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    description: 'Anything Technology',
    category: 'technology',
    sortBy: [
      'top',
      'latest',
    ],
  }],
  user = {
    name: 'Ignatius',
    email: 'ignatius.ukwuoma@andela.com',
    uid: '8575894',
    photo: 'http://andela.com',
  };
